services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: monthly
      POSTGRES_USER: monthly
      POSTGRES_PASSWORD: monthly
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monthly"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/monthly
      SPRING_DATASOURCE_USERNAME: monthly
      SPRING_DATASOURCE_PASSWORD: monthly
      APP_SECURITY_JWT_SECRET: a-very-long-jwt-secret-key-that-meets-256-bit-requirement
      APP_CORS_ALLOWED_ORIGINS: http://localhost:5173
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"
volumes:
  db-data:
