apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: monthly-task-tracker
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://cloudsql-proxy:5432/monthly
  SPRING_DATASOURCE_USERNAME: monthly
  SPRING_DATASOURCE_PASSWORD: change-me
  APP_SECURITY_JWT_SECRET: change-me
