spring:
  application:
    name: monthly-task-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/monthly
    username: monthly
    password: monthly
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    jwt:
      issuer: monthly-task-tracker
      access-token-ttl-minutes: 15
      refresh-token-ttl-days: 7
      secret: change-me
  cors:
    allowed-origins: http://localhost:5173
