spring:
  application:
    name: monthly-task-tracker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/monthly}
    username: ${SPRING_DATASOURCE_USERNAME:monthly}
    password: ${SPRING_DATASOURCE_PASSWORD:monthly}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    jwt:
      issuer: ${APP_SECURITY_JWT_ISSUER:monthly-task-tracker}
      access-token-ttl-minutes: ${APP_SECURITY_JWT_ACCESS_TTL:15}
      refresh-token-ttl-days: ${APP_SECURITY_JWT_REFRESH_TTL:7}
      secret: ${APP_SECURITY_JWT_SECRET:change-me}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
