name: CI - Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build & Test
        run: |
          cd backend
          ./mvnw -q -DskipITs=false -DskipTests=false test package || mvn -q -DskipITs=false -DskipTests=false test package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar
