name: CI - Docker build

on:
  pull_request:
    paths:
      - 'infra/docker/**'
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/ci-docker.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/backend/Dockerfile
          push: false
          tags: backend:ci
      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/frontend/Dockerfile
          push: false
          tags: frontend:ci
